## Scalars (Rank 0 Tensors) in Base Python 

In [3]:
x = 25
type(x)

int

In [4]:
y = 3

In [5]:
py_sum = x + y
py_sum

28

## Scalars in PyTorch ##

The advantage of PyTorch tensors relative to NumPy arrays is that they easily be used for operations on GPU

In [10]:
import torch

In [11]:
x_pt = torch.tensor(25, dtype=torch.float64) # type specification optional, e.g.: dtype=torch.float16
x_pt

tensor(25., dtype=torch.float64)

In [12]:
x_pt.shape

torch.Size([])

## Scalars in TensorFlow (ver 2.0 or later) ##

In [14]:
import tensorflow as tf

In [15]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [16]:
x_tf.shape

TensorShape([])

In [18]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [19]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [20]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [22]:
tf_sum.numpy() # NumPy operations automatically convert tensors to NumPy arrays, and vice versa

np.int16(28)

In [23]:
type(tf_sum.numpy())

numpy.int16

## Vectors and their Transposition ##

In [24]:
import numpy as np

In [25]:
x = np.array([25,2,5]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

In [26]:
len(x)

3

In [27]:
x.shape

(3,)

In [28]:
type(x)

numpy.ndarray

In [29]:
x[0]

np.int64(25)

In [31]:
# Transposition
# Transposing a regular 1-D array has no effect...
x_t = x.T
x_t

array([25,  2,  5])

In [34]:
x_t.shape

(3,)

In [32]:
# ... but it does we use nested "matrix-style" brackets:
y = np.array([[25,2,5]])
y

array([[25,  2,  5]])

In [33]:
y.shape

(1, 3)

In [35]:
# ... but can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [36]:
y_t.shape

(3, 1)

In [37]:
y_t.T # Transpose back

array([[25,  2,  5]])

## Zero Vectors ##

In [38]:
z = np.zeros(3)
z

array([0., 0., 0.])

## Vectors in PyTorch and TensorFlow

In [39]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [40]:
x_tf = tf.Variable([[25,2,5]])
x_tf

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[25,  2,  5]], dtype=int32)>

## L^2 Norm

In [42]:
x

array([25,  2,  5])

In [47]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [43]:
np.linalg.norm(x)

np.float64(25.573423705088842)

## L^1 Norm

In [48]:
x

array([25,  2,  5])

In [49]:
np.abs(25) + np.abs(2) + np.abs(5)

np.int64(32)

## Squared L^2 Norm

In [50]:
x

array([25,  2,  5])

In [51]:
(25**2 + 2**2 + 5**2)

654

In [52]:
np.dot(x,x)

np.int64(654)

## Max Norm or L^∞ Norm

In [53]:
x

array([25,  2,  5])

In [54]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

np.int64(25)

## Orthogonal Vectors

In [55]:
i = np.array([1,0])
i

array([1, 0])

In [ ]:
j = np.array([])