## Scalars (Rank 0 Tensors) in Base Python 

In [1]:
x = 25
type(x)

int

In [2]:
y = 3

In [3]:
py_sum = x + y
py_sum

28

## Scalars in PyTorch ##

The advantage of PyTorch tensors relative to NumPy arrays is that they easily be used for operations on GPU

In [4]:
import torch

In [5]:
x_pt = torch.tensor(25, dtype=torch.float64) # type specification optional, e.g.: dtype=torch.float16
x_pt

tensor(25., dtype=torch.float64)

In [6]:
x_pt.shape

torch.Size([])

## Scalars in TensorFlow (ver 2.0 or later) ##

In [7]:
import tensorflow as tf

In [8]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [9]:
x_tf.shape

TensorShape([])

In [10]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [11]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [12]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [13]:
tf_sum.numpy() # NumPy operations automatically convert tensors to NumPy arrays, and vice versa

np.int16(28)

In [14]:
type(tf_sum.numpy())

numpy.int16

## Vectors and their Transposition ##

In [15]:
import numpy as np

In [16]:
x = np.array([25,2,5]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

In [17]:
len(x)

3

In [18]:
x.shape

(3,)

In [19]:
type(x)

numpy.ndarray

In [20]:
x[0]

np.int64(25)

In [21]:
# Transposition
# Transposing a regular 1-D array has no effect...
x_t = x.T
x_t

array([25,  2,  5])

In [22]:
x_t.shape

(3,)

In [23]:
# ... but it does we use nested "matrix-style" brackets:
y = np.array([[25,2,5]])
y

array([[25,  2,  5]])

In [24]:
y.shape

(1, 3)

In [25]:
# ... but can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [26]:
y_t.shape

(3, 1)

In [27]:
y_t.T # Transpose back

array([[25,  2,  5]])

## Zero Vectors ##

In [28]:
z = np.zeros(3)
z

array([0., 0., 0.])

## Vectors in PyTorch and TensorFlow

In [29]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [30]:
x_tf = tf.Variable([[25,2,5]])
x_tf

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[25,  2,  5]], dtype=int32)>

## L^2 Norm

In [31]:
x

array([25,  2,  5])

In [32]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [33]:
np.linalg.norm(x)

np.float64(25.573423705088842)

## L^1 Norm

In [34]:
x

array([25,  2,  5])

In [35]:
np.abs(25) + np.abs(2) + np.abs(5)

np.int64(32)

## Squared L^2 Norm

In [36]:
x

array([25,  2,  5])

In [37]:
(25**2 + 2**2 + 5**2)

654

In [38]:
np.dot(x,x)

np.int64(654)

## Max Norm or L^∞ Norm

In [39]:
x

array([25,  2,  5])

In [40]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

np.int64(25)

## Orthogonal Vectors

In [41]:
i = np.array([1,0])
i

array([1, 0])

In [42]:
j = np.array([0, 1])
j

array([0, 1])

## Matrices (2D Arrays) NumPy

In [43]:
X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [44]:
X.shape

(3, 2)

In [45]:
X.size

6

In [46]:
X[:0] # Select left column of matrix X

array([], shape=(0, 2), dtype=int64)

In [47]:
X[1,:] # Select middle row of matrix X

array([ 5, 26])

In [48]:
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

## Matrices in PyTorch

In [49]:
X_pt = torch.tensor([[25,2],[5,26],[3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [50]:
X_pt.shape

torch.Size([3, 2])

In [51]:
X_pt[1,:]

tensor([ 5, 26])

In [52]:
X_pt[:,1]

tensor([ 2, 26,  7])

## Matrices in TensorFlow

In [53]:
X_tf = tf.Variable([[25,2], [5,26], [3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [54]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [55]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [56]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>

## Higher-Rank Tensors ##

Rank 4 tensors:
1) images
2) image height and width in pixels, e.g. 28
3) Number of color channels, e.g. RGBa

In [57]:
images_pt = torch.zeros([32,28,28,3])

In [58]:
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [59]:
images_tf = tf.zeros([32,28,28,3])

In [60]:
images_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   

## Segment 2: Common Tensor Operations

Tensor Transposition

In [62]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [63]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [66]:
tf.transpose(X_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]], dtype=int32)>

In [64]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

### Basic Tensor Arithmetic ###

Adding or multiplying with scalar applies operation to all elements and tensor shape is retained:

In [65]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [67]:
X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [68]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [69]:
X_pt*2+2 # Python operators are overloaded; could alternatively use torch.mul() or torch.add()

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [70]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [71]:
X_tf*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [72]:
tf.add(tf.multiply(X_tf,2),2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

if two tensors have the same size, operations are often by default applied element-wise. This is not a matrix multiplication, which we'll cover later,
but is rather called the Hadamard product or simply the element-wise product.

In [73]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [74]:
A = X+2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [75]:
A+X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [76]:
A*X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [77]:
A_pt = X_pt+2

In [78]:
A_pt + X_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [79]:
A_pt * X_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In [80]:
A_tf = X_tf + 2

In [81]:
A_tf + X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [82]:
A_tf * X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]], dtype=int32)>